[package]
name = "translations-analyzer"
version = "0.1.0"
edition = "2024"

[dependencies]
sysinfo = "0.30"
thiserror = "1.0.56"
serde_json = "1.0.139"
regex = "1.10"
rayon = "1.8"
parking_lot = "0.12"
serde = { version = "1.0.228", features = ["derive"] }
once_cell = "1.21.3"
